repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: trailing-whitespace
  -   id: flake8

- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.3.1
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$

- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      args: ["."]