hostname: leaf2

interfaces:
  Loopback0:
    description: Virt Mgmt
    ip_add: 10.254.254.4/32
  Ethernet1:
    ip_add: 10.1.1.3/31
    peer: spine1
    peer_intf: Ethernet2
  Ethernet2:
    ip_add: 10.1.1.11/31
    peer: spine2
    peer_intf: Ethernet2

bgp:
  as_no: 65002
  rid: Loopback0
  peers:
    - intf: Ethernet1
      as_no: 64512
    - intf: Ethernet2
      as_no: 64512
