hostname: spine1

interfaces:
  Loopback0:
    description: Virt Mgmt
    ip_add: 10.254.254.1/32
  Ethernet1:
    ip_add: 10.1.1.0/31
    peer: leaf1
    peer_intf: Ethernet1
  Ethernet2:
    ip_add: 10.1.1.2/31
    peer: leaf2
    peer_intf: Ethernet1

bgp:
  as_no: 64512
  rid: Loopback0
  peers:
    - intf: Ethernet1
      as_no: 65001
    - intf: Ethernet2
      as_no: 65002
